# Generated by Django 6.1.1 on 2026-09-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_zone',
            field=models.CharField(choices=[('near', 'Nearby (0-3 km) - No extra charge'), ('medium', 'Medium (3-8 km) - ₹30 delivery charge'), ('far', 'Far (8+ km) - ₹60 delivery charge')], default='near', max_length=10),
        ),
    ]
